### ISSUE TITLE
`[vite] Internal server error: Failed to resolve import "./out/apps/elements/fullLinkJS.dest/main.js" from "main.js". Does the file exist?`

### ISSUE THREAD

**Issue by anandijain** [AlgebraicJulia/Semagrams.jl#82]
hey, just saw the trailer and it looks super cool. i think i followed the install instructions correctly, but can't seem to get it running.

im on macos if that matters. 
this is what the two terminals show:
terminal 1:
```
anand@anands-MacBook-Pro ~/.j/d/S/scala (main)> mill --watch apps.petri.fullLinkJS
Compiling /Users/anand/.julia/dev/Semagrams.jl/scala/build.sc
[50/96] core.compile 
[info] compiling 41 Scala sources to /Users/anand/.julia/dev/Semagrams.jl/scala/out/core/compile.dest/classes ...
[info] done compiling
[83/96] apps.petri.compile 
[info] compiling 2 Scala sources to /Users/anand/.julia/dev/Semagrams.jl/scala/out/apps/petri/compile.dest/classes ...
[warn] -- Feature Warning: /Users/anand/.julia/dev/Semagrams.jl/scala/apps/petri/src/Main.scala:34:13 
[warn] 34 |implicit def applyStyle(styleA: StyleA): Mod[HtmlElement] =
[warn]    |             ^
[warn]    |Definition of implicit conversion method applyStyle should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
[warn]    |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]    |why the feature should be explicitly enabled.
[warn] one warning found
[info] done compiling
[96/96] apps.petri.fullLinkJS 
Linker: Compute reachability: 1990134 us
Linker: Assemble LinkedClasses: 106835 us
Linker: 2143032 us
Optimizer: Batch mode: true
Optimizer: Incremental part: 410875 us
Optimizer: Optimizing 18198 methods.
Optimizer: Optimizer part: 2159254 us
Optimizer: 2612043 us
Refiner: Compute reachability: 420830 us
Refiner: Assemble LinkedClasses: 17548 us
Refiner: 447336 us
Module Splitter: Calculate Dependency Info: 2680 us
Module Splitter: Analyze Modules: 744 us
Module Splitter: Assemble Modules: 6708 us
Module Splitter: 11024 us
Emitter: Generate Classes: 1347731 us
Emitter: Write trees: 20772 us
Emitter: Class tree cache stats: reused: 0 -- invalidated: 2328
Emitter: Method tree cache stats: reused: 0 -- invalidated: 9592
Emitter: 1397266 us
BasicBackend: Write result: 632502 us
Watching for changes to 6 paths... (Enter to re-run, Ctrl-C to exit)
```

terminal 2
```
anand@anands-MacBook-Pro ~/.j/d/S/scala (main) [SIGINT]> npm run dev

> livechart@0.0.0 dev
> vite


  VITE v3.0.9  ready in 213 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
3:14:25 PM [vite] Internal server error: Failed to resolve import "./out/apps/elements/fullLinkJS.dest/main.js" from "main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/anand/.julia/dev/Semagrams.jl/scala/main.js
  1  |  import { main } from './out/apps/elements/fullLinkJS.dest/main.js'
     |                        ^
  2  |  
  3  |  main(document.getElementById("app-container"))
      at formatError (file:///Users/anand/.julia/dev/Semagrams.jl/scala/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
      at TransformContext.error (file:///Users/anand/.julia/dev/Semagrams.jl/scala/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
      at normalizeUrl (file:///Users/anand/.julia/dev/Semagrams.jl/scala/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40255:33)
      at async TransformContext.transform (file:///Users/anand/.julia/dev/Semagrams.jl/scala/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
      at async Object.transform (file:///Users/anand/.julia/dev/Semagrams.jl/scala/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
      at async loadAndTransform (file:///Users/anand/.julia/dev/Semagrams.jl/scala/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:29)

```

am i doing something wrong?

**Comment by anandijain** [comment]
im dumb, just needed to change the import to `import { main } from './out/apps/petri/fullLinkJS.dest/main.js'`
